# -*- coding: utf-8 -*-
"""inference

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19pPgVU_EHM-BCU6cxir-AcIkuuY8FI06
"""

# -*- coding: utf-8 -*-
import os
import sys
import warnings
import pandas as pd
import numpy as np
import concurrent.futures
from tqdm.auto import tqdm
import torch
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import KFold
from tabpfn import TabPFNRegressor

# 경고 무시
warnings.filterwarnings('ignore')

# ==========================================
# 1. 환경 설정 (Configuration)
# ==========================================

# 경로 설정 (상대 경로)
DATA_DIR = './data'
MODEL_DIR = './models'
OUTPUT_PATH = 'submission.csv'

BASE_MODEL_NAME = 'tabpfn-v2.5-regressor-v2.5_default.ckpt'
LOCAL_BASE_MODEL_PATH = os.path.join(MODEL_DIR, BASE_MODEL_NAME)

if os.path.exists(LOCAL_BASE_MODEL_PATH):
    print(f"✅ Local Base Model Found: {LOCAL_BASE_MODEL_PATH}")
    # 환경 변수 설정으로 다운로드 방지 및 로컬 파일 사용 강제
    os.environ['TABPFN_MODEL_PATH'] = LOCAL_BASE_MODEL_PATH
    os.environ['HF_HUB_OFFLINE'] = '1'
else:
    print(f"⚠️ Local Base Model NOT found at {LOCAL_BASE_MODEL_PATH}")
    print("   System will attempt to download the model from HuggingFace.")
    # 파일이 없으면 None으로 두어 라이브러리 기본 동작(다운로드) 유도

TRAIN_PATH = os.path.join(DATA_DIR, 'train.csv')
TEST_CSV_PATH = os.path.join(DATA_DIR, 'test.csv')
TEST_FOLDER_PATH = os.path.join(DATA_DIR, 'test')
MATCH_INFO_PATH = os.path.join(DATA_DIR, 'match_info.csv')

# Device 설정
DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'

# ==========================================
# 2. TabPFN 패치 및 유틸리티 (Utils)
# ==========================================
# train.py와 동일한 환경 구성을 위해 패치 적용

try:
    import tabpfn_common_utils.telemetry.interactive.flows as flows
    flows._trigger_prompts = lambda *args, **kwargs: False
except Exception:
    pass

try:
    from tabpfn.preprocessors.kdi_transformer import KDITransformerWithNaN
    def explicit_init(self, alpha=1.0, output_distribution='normal'):
        super(KDITransformerWithNaN, self).__init__(alpha=alpha, output_distribution=output_distribution)
        self.alpha = alpha
        self.output_distribution = output_distribution
    KDITransformerWithNaN.__init__ = explicit_init
except ImportError:
    pass

# ==========================================
# 3. 데이터 로드 및 전처리 (Preprocessing)
# ==========================================
# train.py와 동일한 로직을 유지해야 함

def read_csv_file(args):
    file_path, base_folder = args
    try:
        full_path = file_path.replace('./test', base_folder)
        return pd.read_csv(full_path, engine='pyarrow', dtype_backend='pyarrow')
    except:
        return None

def load_test_data_fast(test_csv_path, test_folder_path, max_workers=16):
    test_meta_df = pd.read_csv(test_csv_path)
    tasks = [(row['path'], test_folder_path) for _, row in test_meta_df.iterrows()]

    with concurrent.futures.ThreadPoolExecutor(max_workers=max_workers) as executor:
        results = list(tqdm(executor.map(read_csv_file, tasks), total=len(tasks), desc="Loading Test Data"))

    valid_dfs = [df for df in results if df is not None]
    if valid_dfs:
        return pd.concat(valid_dfs, ignore_index=True), test_meta_df
    else:
        raise ValueError("No files loaded.")

def assign_tactical_zone(x, y):
    if x < 35: x_zone = 0
    elif x < 70: x_zone = 1
    else: x_zone = 2
    if y < 22.66: y_zone = 0
    elif y < 45.33: y_zone = 1
    else: y_zone = 2
    return x_zone * 3 + y_zone

def is_in_penalty_box(x, y):
    return 1 if (x >= 88.5) and (13.84 <= y <= 54.16) else 0

def create_tabular_features(df, is_train=True):
    mode = 'Train' if is_train else 'Test'
    # Inference 시 로그 출력 최소화

    df = df.sort_values(['game_episode', 'action_id']).reset_index(drop=True)
    grouped = df.groupby('game_episode')
    features = []

    for name, group in tqdm(grouped, desc=f"Processing {mode}"):
        last_event = group.iloc[-1]
        prev_event = group.iloc[-2] if len(group) > 1 else last_event

        curr_id = last_event['action_id']
        prev_id = prev_event['action_id']
        action_id_gap = max(0, (curr_id - prev_id) - 1)

        time_diff = max(0, last_event['time_seconds'] - prev_event['time_seconds'])
        time_per_missing_action = time_diff / (action_id_gap + 1)

        curr_x, curr_y = last_event['start_x'], last_event['start_y']
        prev_end_x, prev_end_y = prev_event['end_x'], prev_event['end_y']
        prev_dx = prev_event['end_x'] - prev_event['start_x']
        prev_dy = prev_event['end_y'] - prev_event['start_y']

        dist_from_prev = np.sqrt((curr_x - prev_end_x)**2 + (curr_y - prev_end_y)**2) if len(group) > 1 else 0
        prev_dist = np.sqrt(prev_dx**2 + prev_dy**2)

        prev_angle = np.arctan2(prev_dy, prev_dx)
        goal_angle = np.arctan2(34 - curr_y, 105 - curr_x)
        move_angle = np.arctan2(curr_y - prev_end_y, curr_x - prev_end_x)

        direction_consistency = np.cos(prev_angle - goal_angle)
        angle_diff = np.abs(goal_angle - move_angle)
        dist_to_goal = np.sqrt((105 - curr_x)**2 + (34 - curr_y)**2)

        curr_type = str(last_event['type_name'])
        curr_result = str(last_event.get('result_name', 'None'))
        event_type = f"{curr_type}_{curr_result}"
        prev_type_str = str(prev_event['type_name'])
        prev_result_str = str(prev_event.get('result_name', 'None'))
        prev_event_type = f"{prev_type_str}_{prev_result_str}"

        is_same_team = 1 if last_event['team_id'] == prev_event['team_id'] else 0
        zone_id = assign_tactical_zone(curr_x, curr_y)
        in_box = is_in_penalty_box(curr_x, curr_y)

        row = {
            'game_episode': name,
            'game_id': last_event['game_id'],
            'start_x': curr_x, 'start_y': curr_y, 'time_seconds': last_event['time_seconds'],
            'prev_x': prev_event['start_x'], 'prev_y': prev_event['start_y'],
            'event_type': event_type, 'prev_event_type': prev_event_type,
            'period_id': last_event['period_id'], 'team_id': last_event['team_id'], 'player_id': last_event['player_id'],
            'is_same_team': is_same_team, 'zone_id': zone_id, 'in_box': in_box,
            'time_since_prev': time_diff, 'dist_from_prev': dist_from_prev, 'prev_dist': prev_dist,
            'action_id_gap': action_id_gap, 'time_per_missing_action': time_per_missing_action,
            'direction_consistency': direction_consistency, 'move_angle': move_angle, 'angle_diff': angle_diff,
            'dist_to_goal': dist_to_goal, 'angle_to_goal': goal_angle,
        }

        if is_train:
            row['delta_x'] = last_event['end_x'] - last_event['start_x']
            row['delta_y'] = last_event['end_y'] - last_event['start_y']

        features.append(row)

    return pd.DataFrame(features)

def merge_match_info(feat_df, info_df):
    merged = pd.merge(feat_df, info_df, on='game_id', how='left')
    merged['is_home'] = (merged['team_id'] == merged['home_team_id']).astype(int)
    merged['opponent_id'] = np.where(merged['is_home'] == 1, merged['away_team_id'], merged['home_team_id'])
    return merged

# ==========================================
# 4. 추론 메인 함수 (Inference Main)
# ==========================================

def run_inference():
    print("\n>>> [1/4] Loading Data for Support Set & Inference...")
    # Inference 시에도 LabelEncoder 정합성과 TabPFN의 Support Set(참조 데이터) 구성을 위해 Train 데이터를 로드합니다.
    # 이는 학습(Weight Update)을 위함이 아니라, 모델의 Context 제공을 위함입니다.
    train_df = pd.read_csv(TRAIN_PATH)
    test_df, test_meta_df = load_test_data_fast(TEST_CSV_PATH, TEST_FOLDER_PATH)

    match_info = pd.read_csv(MATCH_INFO_PATH)
    match_cols = ['game_id', 'home_team_id', 'away_team_id', 'venue']
    match_info = match_info[match_cols]

    print("\n>>> [2/4] Preprocessing & Feature Engineering...")
    train_feat = create_tabular_features(train_df, is_train=True)
    test_feat = create_tabular_features(test_df, is_train=False)

    train_feat = merge_match_info(train_feat, match_info)
    test_feat = merge_match_info(test_feat, match_info)

    # 변수 변환
    target_cols_log = ['prev_dist', 'dist_from_prev', 'time_since_prev', 'time_per_missing_action']
    for col in target_cols_log:
        train_feat[col+'_log1p'] = np.log1p(train_feat[col])
        test_feat[col+'_log1p'] = np.log1p(test_feat[col])

    target_cols_cat = [
        'event_type', 'prev_event_type', 'in_box', 'zone_id',
        'is_same_team', 'period_id', 'team_id', 'player_id',
        'venue', 'opponent_id', 'is_home'
    ]

    # Label Encoding (Train 기준 Fit, Test Transform)
    for col in target_cols_cat:
        new_col = col + '_cat'
        le = LabelEncoder()
        # Train과 Test의 범주를 모두 포함하여 fit (Unknown 방지)
        all_vals = pd.concat([train_feat[col], test_feat[col]]).fillna(-1).astype(str)
        le.fit(all_vals)
        train_feat[new_col] = le.transform(train_feat[col].fillna(-1).astype(str))
        test_feat[new_col] = le.transform(test_feat[col].fillna(-1).astype(str))

    base_features = [
        'start_x', 'start_y', 'time_seconds', 'prev_x', 'prev_y',
        'dist_to_goal', 'angle_to_goal', 'direction_consistency', 'move_angle', 'angle_diff',
        'action_id_gap', 'time_per_missing_action'
    ]
    log_features = [col + '_log1p' for col in target_cols_log]
    cat_features = [col + '_cat' for col in target_cols_cat]
    final_features = base_features + log_features + cat_features

    X = train_feat[final_features]
    y_dx = train_feat['delta_x']
    y_dy = train_feat['delta_y']
    X_test = test_feat[final_features]

    # ==========================================
    # 5. 5-Fold 모델 로드 및 앙상블 추론
    # ==========================================
    print("\n>>> [3/4] Running Inference with Saved Models (Ensemble)...")

    final_pred_dx = np.zeros(len(X_test))
    final_pred_dy = np.zeros(len(X_test))

    kf = KFold(n_splits=5, shuffle=True, random_state=42)

    for fold, (train_idx, val_idx) in enumerate(kf.split(X, y_dx)):
        print(f"  > Processing Fold {fold}...")

        # TabPFN에 Support Set(참조 데이터) 제공을 위해 해당 Fold의 Train 데이터를 준비
        X_train_fold = X.iloc[train_idx]
        y_dx_train_fold = y_dx.iloc[train_idx]
        y_dy_train_fold = y_dy.iloc[train_idx]

        # --- Delta X Inference ---
        model_arg = LOCAL_BASE_MODEL_PATH if os.path.exists(LOCAL_BASE_MODEL_PATH) else None

        reg_dx = TabPFNRegressor(
            device=DEVICE,
            model_path=model_arg, # <--- 이 부분 추가
            fit_mode='low_memory'
        )
        # 1. Support Set 등록 (이 과정은 학습이 아니라 참조 데이터 등록입니다)
        reg_dx.fit(X_train_fold, y_dx_train_fold)
        # 2. Fine-tuning된 가중치 로드 (저장된 학습 결과 덮어쓰기)
        model_path_dx = os.path.join(MODEL_DIR, f'tabpfn_dx_fold{fold}.pt')
        reg_dx.model_.load_state_dict(torch.load(model_path_dx, map_location=DEVICE))
        # 3. 예측
        reg_dx.model_.eval()
        pred_dx = reg_dx.predict(X_test, output_type="median")
        final_pred_dx += pred_dx / 5

        model_arg = LOCAL_BASE_MODEL_PATH if os.path.exists(LOCAL_BASE_MODEL_PATH) else None

        reg_dy = TabPFNRegressor(
            device=DEVICE,
            model_path=model_arg,
            fit_mode='low_memory'
        )
        reg_dy.fit(X_train_fold, y_dy_train_fold)

        model_path_dy = os.path.join(MODEL_DIR, f'tabpfn_dy_fold{fold}.pt')
        reg_dy.model_.load_state_dict(torch.load(model_path_dy, map_location=DEVICE))

        reg_dy.model_.eval()
        pred_dy = reg_dy.predict(X_test, output_type="median")
        final_pred_dy += pred_dy / 5

    # ==========================================
    # 6. 결과 저장
    # ==========================================
    print("\n>>> [4/4] Saving Submission File...")

    # 좌표값 계산 및 클리핑 (경기장 규격 벗어나지 않도록)
    final_pred_x = np.clip(test_feat['start_x'] + final_pred_dx, 0, 105)
    final_pred_y = np.clip(test_feat['start_y'] + final_pred_dy, 0, 68)

    submission_df = pd.DataFrame({
        'game_episode': test_feat['game_episode'],
        'end_x': final_pred_x,
        'end_y': final_pred_y
    })

    # 제출 형식 맞추기 (test.csv 순서 보장)
    final_submission = pd.merge(test_meta_df[['game_episode']], submission_df, on='game_episode', how='left')
    final_submission.to_csv(OUTPUT_PATH, index=False)

    print(f"✅ Submission Saved Successfully: {OUTPUT_PATH}")

if __name__ == '__main__':
    run_inference()