# -*- coding: utf-8 -*-
"""run

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_wRh2JjVzb-BqqXrtuL4kACCSG7746NY
"""

!pip install -r requirements.txt

!pip install tabpfn pyarrow

!unzip -o -q /content/data/test.zip -d /content/data/test

!python train.py

!python inference.py

